
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

  traefik:
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.ssp.docker.localhost`)"
    ports:
      - "443:443"
      - "80:80"

  nginx:
    labels:
      - "traefik.http.routers.nginx.rule=Host(`ssp.docker.localhost`)"
