security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        database_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: database_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                token_provider:
                    doctrine: true
            logout:
                path: /logout
    access_control:
        - { path: '^/$', roles: ROLE_USER }
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: '^/super-admin', roles: ROLE_SUPER_ADMIN }
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
